Repository Sum-nail/sum-nail-client, pull requests merged in 2024-01, with the labels that each got.

#5 Feat/#1 메인, 검색 페이지 UI 구현
  .gitignore
  app/page.tsx
  app/search/page.tsx
  components/common/card.tsx
  components/common/stationRecord.tsx
  components/common/stationSearchBar.tsx
  next.config.js
  package.json
  public/icons/ic_back.svg
  public/icons/ic_delete.svg
  public/icons/ic_gray_flower.svg
  public/icons/ic_pink_flower.svg
  public/icons/index.tsx
  public/icons/logo.png
  public/icons/map_pin.svg
  public/icons/money.svg
  styles/styles.d.ts
  styles/theme.ts
Labels: fix, UI

#7 Feat/#6 API 세팅
  api/common/index.tsx
  api/common/types.tsx
  api/index.tsx
  api/nail-shops/index.tsx
  api/nail-shops/types.tsx
  api/users/index.tsx
  api/users/types.tsx
  app/page.tsx
  hooks/index.ts
  hooks/index.tsx
  package.json
  yarn.lock
Labels: feat

#10 Feat/#3
  app/mypage/EmptyBox.tsx
  app/mypage/ProfileCard.tsx
  app/mypage/StoredList.tsx
  app/mypage/page.tsx
  components/common/NailSelect.tsx
  components/myPage/SocialLoginBtn.tsx
  public/icons/back.svg
  public/icons/flower_colored.svg
  public/icons/googleLogin.svg
  public/icons/index.tsx
  public/icons/kakaoLogin.svg
  public/icons/logo.svg
  public/icons/nail-art_gray.svg
  public/icons/profile_default.svg
  styles/styles.d.ts
  styles/theme.ts
Labels: feat, design, chore

#9 Feat/#2
  app/detail/page.tsx
  app/page.tsx
  app/search/page.tsx
  components/Layout.tsx
  components/common/LoginModal.tsx
  components/common/LongBottomButton.tsx
  components/common/ModalPotal.tsx
  components/common/card.tsx
  components/common/stationSearchBar.tsx
  components/detail/DefaultBottomButton.tsx
  components/detail/DetailNav.tsx
  components/detail/ImageCarousel.tsx
  components/detail/NailCost.tsx
  components/detail/NailInfo.tsx
  components/detail/NailInfo/ ShortcutsLink.tsx
  components/detail/OpeningHour.tsx
  components/detail/StoreMap.tsx
  components/detail/ThisMonthNail.tsx
  package.json
  public/icons/Rectangle 6452.svg
  public/icons/User.svg
  public/icons/ic_Calendar.svg
  public/icons/ic_Clock.svg
  public/icons/ic_CreditCard.svg
  public/icons/ic_MapPin.svg
  public/icons/ic_Navi.svg
  public/icons/ic_back_button.svg
  public/icons/ic_bookmark.svg
  public/icons/ic_person.svg
  public/icons/ic_sn_logotype.svg
  public/icons/image.svg
  public/icons/index.tsx
  public/images/ic_sn_logotype.png
  public/images/index.tsx
  styles/styles.d.ts
  styles/theme.ts
  yarn.lock
Labels: feat, UI, detail
